language: cpp
compiler:
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-regex1.48-dev libboost-test1.48-dev
before_script:
  - ./autogen.sh
script:
  - ./configure && make && make check
branches:
  only:
    - master
